compressionLevel: 5

enableGlobalCache: false

logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules
npmMinimalAgeGate: 1440  
enableScripts: false
yarnPath: .yarn/releases/yarn-4.12.0.cjs
